/** Service areas for SEO, AEO, and location pages */

export const REGIONS = [
    {
        id: "sutherland-shire",
        name: "Sutherland Shire",
        blurb:
            "Our home base. Personalised NDIS, nursing and aged care across the Shire.",
        suburbs: [
            "Sutherland",
            "Cronulla",
            "Miranda",
            "Caringbah",
            "Gymea",
            "Kirrawee",
            "Jannali",
            "Como",
            "Oyster Bay",
            "Sylvania",
            "Sylvania Waters",
            "Taren Point",
            "Woolooware",
            "Bundeena",
            "Engadine",
            "Heathcote",
            "Loftus",
            "Menai",
            "Illawong",
            "Bangor",
            "Woronora",
            "Woronora Heights",
            "Yarrawarrah",
            "Waterfall",
            "Kurnell",
            "Lilli Pilli",
            "Port Hacking",
            "Dolans Bay",
            "Burraneer",
            "Grays Point",
            "Gymea Bay",
            "Kangaroo Point",
            "Bonnet Bay",
            "Alfords Point",
            "Barden Ridge",
            "Lucas Heights",
            "Sandy Point",
        ],
    },
    {
        id: "illawarra",
        name: "Illawarra",
        blurb:
            "In-home nursing and disability support from Wollongong to the northern Illawarra.",
        suburbs: [
            "Wollongong",
            "Figtree",
            "Unanderra",
            "Fairy Meadow",
            "Corrimal",
            "Thirroul",
            "Bulli",
            "Woonona",
            "Austinmer",
            "Helensburgh",
            "Dapto",
            "Shellharbour",
            "Warrawong",
            "Port Kembla",
            "Kiama",
            "Albion Park",
            "Oak Flats",
            "Berkeley",
            "Coniston",
            "Gwynneville",
            "Keiraville",
            "Mount Keira",
            "North Wollongong",
            "South Wollongong",
            "Towradgi",
            "Balgownie",
            "East Corrimal",
            "Stanwell Park",
            "Coalcliff",
        ],
    },
    {
        id: "central-coast",
        name: "Central Coast",
        blurb:
            "NDIS and clinical support across Gosford, Wyong and surrounding coastal suburbs.",
        suburbs: [
            "Gosford",
            "Wyoming",
            "East Gosford",
            "West Gosford",
            "Erina",
            "Terrigal",
            "Woy Woy",
            "Umina Beach",
            "Ettalong Beach",
            "Avoca Beach",
            "Kincumber",
            "Kariong",
            "Narara",
            "Niagara Park",
            "Lisarow",
            "Ourimbah",
            "Wyong",
            "Tuggerah",
            "The Entrance",
            "Long Jetty",
            "Toukley",
            "Budgewoi",
            "Lake Haven",
            "Warnervale",
            "Bateau Bay",
            "Killarney Vale",
            "Berkeley Vale",
            "Chittaway Bay",
            "Point Clare",
            "Somersby",
        ],
    },
    {
        id: "greater-sydney",
        name: "Greater Sydney",
        blurb:
            "Flexible nursing and support across selected Greater Sydney suburbs.",
        suburbs: [
            "Sydney CBD",
            "Surry Hills",
            "Newtown",
            "Parramatta",
            "Liverpool",
            "Bankstown",
            "Hurstville",
            "Kogarah",
            "Rockdale",
            "Brighton-Le-Sands",
            "Sans Souci",
            "Blakehurst",
            "Peakhurst",
            "Penshurst",
            "Mortdale",
            "Oatley",
            "Riverwood",
            "Beverly Hills",
            "Kingsgrove",
            "Bexley",
            "Arncliffe",
            "Wolli Creek",
            "Mascot",
            "Botany",
            "Maroubra",
            "Randwick",
            "Bondi",
            "Bondi Junction",
            "Eastern Suburbs",
            "Inner West",
            "St George",
            "Canterbury-Bankstown",
        ],
    },
];

export const ALL_SUBURBS = REGIONS.flatMap((r) =>
    r.suburbs.map((s) => ({ suburb: s, region: r.name, regionId: r.id }))
);

export function slugifySuburb(name) {
    return name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "");
}

export function findSuburb(slug) {
    return ALL_SUBURBS.find((s) => slugifySuburb(s.suburb) === slug) || null;
}
